version: "2"
services:
     frontend:
       image: httpd:2.4
       ports:
       - "8080:80"
       volumes:
       - ./VIA/:/usr/local/apache2/htdocs
     backend:
       image: httpd:2.4
       ports:
       - "8081:80"
       volumes:
       - ./Administrador_definitivo/:/usr/local/apache2/htdocs
     api:
       build: .
       ports:
         - "3000:3000"
       depends_on:
         - db
     db:
        image: mongo
        ports:
         - "27017:27017"
